
# Project information
site_name: Mkdocs Svelte
site_url: https://mkdocs-svelte.gxzv.com
site_author: JU Chengren

# Repository
repo_name: lshiy/mkdocs-svelte
repo_url: https://github.com/lshiy/mkdocs-svelte

# Home
home_title: 文档从未如此简单
home_description: Mkdocs Svelte 是一个基于 SvelteKit 的文档站点生成器，灵感来源于 <a href='https://github.com/squidfunk/mkdocs-material' target='_blank'>mkdocs-material</a>。使用 <a href='https://mdsvex.pngwn.io/' target='_blank'>mdsvex</a> 进行 Markdown 渲染，支持在文档中无缝集成 Svelte 组件，为你提供更灵活、强大的文档编写体验。

# Page tree
# nav:
#   - Home: /
#   - Test:
#     - test/index.md
#     - Secondary: test/index2.md

# Page tree
nav:
  - 主页: /
  - 快速开始:
    - 安装: getting-started.md